gcettuzz/chuchipirat

.gitignore, package.json, src/components/Event/event.class.js, src/components/Event/event.jsx, src/components/Firebase/firebase.class.js, src/components/Home/home.jsx, src/components/Menuplan/menuplan.class.js, src/components/Menuplan/menuplan.jsx, src/components/Navigation/navigation.jsx, src/components/QuantityCalculation/quantityCalculation.class.js, src/components/Recipe/recipe.class.js, src/components/Recipe/recipe.jsx, src/components/Recipe/recipes.jsx, src/components/Session/withAuthentication.js, src/components/Shared/feed.class.js, src/components/Shared/searchInputWithButton.jsx, src/components/ShoppingList/shoppingList.class.js, src/components/Temp/temp.jsx, src/components/User/user.class.js, src/constants/firebaseEvents.js, src/constants/text.js
=> Feature 8: Verbesserung der Rezeptübersicht

src/components/Event/event.jsx, src/components/Event/events.jsx, src/components/Firebase/firebase.class.js, src/components/Home/home.jsx, src/components/Recipe/recipe.class.js, src/components/Recipe/recipe.jsx, src/constants/text.js
=> #24 zu viele reads bei auth user

src/components/Event/event.class.js, src/components/Event/event.jsx, src/components/Firebase/firebase.class.js, src/components/Recipe/recipe.class.js, src/components/Recipe/recipe.jsx, src/components/Session/withAuthentication.js, src/components/User/user.class.js, src/components/User/userProfile.jsx, src/constants/firebaseEvents.js, src/constants/styles.js, src/constants/text.js
=> #16 aktualisieren löschen von bildern

package.json, src/components/App/App.css, src/components/Event/event.class.js, src/components/Firebase/firebase.class.js, src/components/Navigation/dialogRefreshApp.jsx, src/components/Navigation/navigation.jsx, src/components/Recipe/recipe.class.js, src/constants/firebaseEvents.js, src/constants/localStorage.js, src/constants/text.js
Mechanismus um User darauf hinzuweisen, wenn auf dem Server eine neuere Version der App liegt.
close #17
=> #17: Force Refresh:

src/components/Recipe/recipe.class.js, src/components/Recipe/recipe.jsx, src/components/Shared/searchInputWithButton.jsx
=> #29 tags werden nicht gespeichert

src/components/Recipe/recipe.class.js
Sichergestellt, dass immer mindestens eine Zutat /Z ubereitungsschritt vorhanden ist (auch wenn leer).
close #30
=> Korrektur Bug #30

src/components/Product/dialogProduct.jsx, src/components/Product/product.class.js, src/components/Product/products.jsx, src/components/Recipe/recipe.jsx
close #31
close #32 
31: Führende und schliessende Leerzeichen werden nicht entfernt
32: Löschen von Einheiten und Abteilungen nicht möglich
=> #31 + #32 Bugs im Umfeld Produkte

src/components/Product/dialogProduct.jsx, src/components/Product/products.jsx, src/components/Recipe/recipe.jsx, src/components/ShoppingList/dialogShoppingListItem.jsx, src/constants/text.js
Fix --> Check, dass keine Produkte angelegt werden können, mit Namen, die bereits existieren
close #45
=> #45 Bug Mehrere Produkte mit selben Namen. 

package.json, src/components/Admin/admin.jsx, src/components/Admin/feedDelete.jsx, src/components/Admin/whereUsed.jsx, src/components/App/App.js, src/components/Firebase/firebase.class.js, src/components/Menuplan/menuplan.jsx, src/components/Navigation/navigation.jsx, src/components/Product/product.class.js, src/components/Recipe/recipe.class.js, src/components/Recipe/recipeCard.jsx, src/components/Recipe/recipeDrawer.jsx, src/components/Unit/unitConversion.jsx, src/constants/routes.js, src/constants/text.js
WhereUsed neu dazugekommen und Admin Screen aufgeräumt
close #38
=> #38 Verfolgungsnachweis Rezepte und Produkte

src/components/Event/event.class.js, src/components/Event/event.jsx
Korrektur, damit die Anzahl Teilnehmden immer richtig berechnet werden (und kein NaN entsteht.)
Close #44
=> Fix: Statistik Anzahl Teilnehmede

src/components/Product/dialogProduct.jsx, src/components/Recipe/recipe.jsx
Produkte können nun wieder geändert werden (wenn sie bereits erfasst sind)
close #52
=> Bug behoben

src/components/Event/events.jsx
Übergabeparamter "visible" sauber übergeben.
close #70
=> BugFix Button visibility

src/constants/defaultValues.js
URL auf Wordpress angepasst
close #81
=> Anpassung Helpcenter URL

src/components/QuantityCalculation/quantityCalculation.jsx, src/components/QuantityCalculation/quantityCalculationPdf.jsx, src/constants/stylesPdf.js
Ein allfälliger Rezepthinweis wird nun auf der Mengenberechnung angezeigt. Seite wie auch PDF.
close #69
=> #69 Rezept Hinweis anzeigen bei Mengenberechnung

package.json
=> 88 bug anpassung der versionsnummer

src/components/ShoppingList/shoppingListPdf.jsx, src/constants/stylesPdf.js
Stylesheet für PDF Export Shoppinglist wurde angepasst.
close #92
=> Fehlerhafter PDF Export

.gitignore, src/components/404/404.jsx, src/components/Admin/mergeProducts.jsx, src/components/App/App.css, src/components/App/App.js, src/components/AuthServiceHandler/verifyEmail.jsx, src/components/Firebase/firebase.class.js, src/components/Navigation/navigation.jsx, src/components/Product/product.class.js, src/components/Session/withEmailVerification.jsx, src/components/SignUp/signUp.jsx, src/constants/routes.js, src/constants/text.js
Nachdem der User registriert wurde und auf den Authentifizierungslink klickt, konnte das Public-Profile nicht sauber gelesen werden. Dieser Fix macht die Anmeldung ohne Stolpersteine wieder möglich.
close #129
=> Bug 129 -  Fehler bei der Authentifizierung der E-Mailadresse

.gitignore, src/components/QuantityCalculation/quantityCalculation.jsx, src/components/Recipe/recipe.jsx, src/components/Recipe/recipePdf.jsx, src/constants/styles.js
Fix damit bei Rezepten der PDF-Export (einzeln) wieder möglich ist. Zusätzlicher Style-Fix für die Mengenberechnungsanzeige (Bug aus dem Feature-Request 120 (Skalierungsfaktoren einblenden).
close #124
=> Bug 124 - Druckversion bei Rezepten funktioniert nicht

src/components/AuthServiceHandler/verifyEmail.jsx, src/components/Navigation/navigation.jsx, src/components/Session/withEmailVerification.jsx
=> 129 bug fehler bei den e mailverifizierung

.gitignore, src/components/Admin/feedDelete.jsx, src/components/App/App.js, src/components/Firebase/firebase.class.js, src/components/Home/home.jsx, src/components/Shared/feed.class.js, src/constants/text.js
Änderung der Cloud-Function Logik und es können nun einzelne Feeds gelöscht werden.
close #137
=> Anpassung des Feed-Delete

src/components/Navigation/navigation.tsx
Im Menü, statt nur das Icon, den Link auf das gesamte Listelement erweitern.
closes #153
=> Erweiterung des klickbaren Elements

package.json, src/components/Firebase/Db/firebase.db.recipe.class.ts, src/components/Recipe/recipe.class.ts, src/components/Recipe/recipe.view.tsx
=> Leere Mengen bei Materialien (Rezepte) abfangen

src/components/User/user.class.ts, src/components/User/userProfile.tsx
=> #156 profil kann ohne vornamen und anzeigename gespeichert werden

src/components/Event/ShoppingList/shoppingListCollection.class.ts, src/components/Firebase/Db/firebase.db.recipeShort.variant.class.ts
Minimale Korrekturen rund um die Shoppingliste
=> #188 Fehler bei fix eingeplanten Portionen
